#!/bin/bash

sudo chmod 777 /home/pi/Photobooth/*
mkdir /home/pi/Photobooth/resized
mkdir /home/pi/Photobooth/photobooth

sudo apt install  python3-picamera python-pil libgtk-3-dev python3-gi 
sudo apt-install --no-install-recommends xserver-xorg
sudo apt install xinit

sudo cp photobooth.service /etc/systemd/system/photobooth.service
sudo systemctl daemon-reload
sudo systemctl enable photobooth.service


